version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shortlinks

    # volumes:
    #   - postgres_data:/bitnami/postgresql/data

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
#     volumes:
#       - redis_data:/bitnami/redis/data

# volumes:
#   postgres_data:
#   redis_data: